version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: ciabot_postgres_adhoc
    restart: always
    env_file: 
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ciabot_network_adhoc
    ports:
      - "5434:5432"

  ciabot:
    build: .
    container_name: ciabot_public_adhoc
    restart: always
    env_file: 
      - .env
    networks:
      - ciabot_network_adhoc
    depends_on:
      - db
    ports:
      - "82:3001"

volumes:
  pgdata:

networks:
  ciabot_network_adhoc:
    external: true