version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: ciabot_postgres_dev
    restart: always
    env_file: 
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ciabot_network_dev
    ports:
      - "5435:5432"

  ciabot:
    build: .
    container_name: ciabot_public_dev
    restart: always
    env_file: 
      - .env
    networks:
      - ciabot_network_dev
    depends_on:
      - db
    ports:
      - "83:3001"

volumes:
  pgdata:

networks:
  ciabot_network_dev:
    external: true