name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t cia_bot_public .

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEY }}

    - name: Deploy to DigitalOcean Droplet
      run: |
        # Stop existing container if running
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
        'docker stop cia_bot_public || true && docker rm cia_bot_public || true'
        
        # Pull latest image
        scp -o StrictHostKeyChecking=no -r . ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/cia_bot_public

        # Build and run the container on the droplet
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
        'cd /cia_bot_public && docker build -t cia_bot_public . && docker run -d --name ciabot -p 80:80 cia_bot_public'
