name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify current directory
      run: pwd

    - name: List files in current directory
      run: ls -la

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Ensure we are in the repository root
      run: cd $GITHUB_WORKSPACE && ls -la

    - name: Build Docker image
      run: docker-compose build

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEY }}

    - name: Deploy to DigitalOcean Droplet
      run: |
        # Stop existing container if running
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
        'docker-compose down || true'
        
        # Deploy the new version (scp will copy the whole project to your droplet)
        scp -o StrictHostKeyChecking=no -r * ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/root/ciabot-public/

        # Build and run Docker Compose on the droplet
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
        'cd /root/ciabot-public && docker-compose up -d --build'
